---
title: "Pizza Plot"
output: html_document
date: '2022-05-11'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(worldfootballR)
library(ggshakeR)
```

```{r}
data1 <- fb_player_scouting_report("https://fbref.com/en/players/17695062/Emile-Smith-Rowe", pos_versus = "primary")

data2 <- fb_player_scouting_report("https://fbref.com/en/players/48a5a5d6/Martinelli", pos_versus = "primary")

data <- rbind(data1, data2)

comp_pizza <- plot_pizza(data = data, type = "comparison", template = "forward",
                         player_1 = "Emile Smith Rowe", player_2 = "Martinelli", 
                         season_player_1 = "Last 365 Days", season_player_2 = "Last 365 Days",
                         colour_compare = "#EF0107", theme = "black")
comp_pizza

```

```{r}
# install.packages("ggplot2")
library(tidyverse)
#' The "bg" parameter is to be set w.r.t the theme of the plot.
#' "dark" = "#0d1117"
#' "black" = "black"
#' "white" = "white"
ggsave("Smith Rowe and Martinelli.png", bg = "black", width = 3000, height = 2800, units = "px") 
```

