---
title: "Thierry Henry Goals and Assists"
author: "Andres Gonzalez"
date: "1/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages

```{r message = FALSE, warning=FALSE}
library(worldfootballR)
pacman::p_load(tidyverse, polite, scales, ggimage, rvest, 
               glue, extrafont, showtext, ggrepel, magick, 
               ggforce, lubridate, cowplot, patchwork, rlang)
library(ggtext)
loadfonts()
```

# Data

```{r}
th_GA <- fb_player_season_stats("https://fbref.com/en/players/c0c5ee74/Thierry-Henry", stat_type = 'standard') %>%
  filter(Squad == "Arsenal") %>%
  filter(Comp == "1. Premier League") %>%
  slice(-c(9))
```


# Clean

```{r}
th_GA <- th_GA %>%
  select(player_name, Squad, Season, Gls, Ast) %>%
  pivot_longer(cols = -c(player_name,Squad,Season), names_to="GA", values_to="Count") 
```


# Visualization

```{r}
th_GA_plot <- th_GA %>%
  mutate(Season = factor(Season, levels = rev(unique(Season)), ordered=TRUE)) %>%
  ggplot(aes(fill=forcats::fct_rev(GA), y=Season, x= Count, color=GA)) +
  geom_bar(position="stack", stat="identity",width = 0.7, size = 0.5) +
  geom_text(aes(label=Count), color = "#D4D6D1", size = 4, hjust = 1.5, vjust = 0.5, position ="stack") +
  geom_text(aes(label = stat(x), group = Season), stat = 'summary', fun = sum, hjust = -0.5, color = "#D4D6D1", size = 4) +
  scale_colour_manual(values=c("black", "#C69A5D")) +
  scale_fill_manual(values = c("#013474", "#DB0008")) +
  scale_x_continuous(expand = c(0.01,0),
                     limits = c(0,50)) + 
  labs(x = NULL, y = NULL, 
       title = "THIERRY HENRY <span style = 'color: #013474' >GOALS</span> & <span style = 'color: #DB0008' >ASSISTS</span>",
       subtitle = "8 Seasons | ARSENAL FC",
       caption ="<i>Data:fbref | Statsbomb <br> Twitter:@AndresAnalytics </i>") +
  theme_void() +
  theme(text = element_text(family = "Georgia"),
        plot.background = element_rect(fill = "#110F14"),
        plot.title = element_markdown(color = "white", face = "bold", size = 20,margin = margin(b=5)),
        plot.title.position = "plot",
        plot.subtitle = element_text(color = "white",margin = margin(b=5)),
        plot.caption = element_markdown(color = "white", hjust = 0),
        plot.caption.position = "plot",
        panel.grid.major = element_line(color = "grey25", linetype = "dotted"),
        panel.grid.minor = element_blank(),
        axis.text.x = element_blank(),
        axis.text = element_text(color = "white"),
        legend.position = "none") 
  
```


# Save

```{r}
ggsave(plot = th_GA_plot, "...../Thierry Henry Goals and Assists.png",
       height = 4, width = 6)
```



